"""Initial migration

Revision ID: 711f5e9f2925
Revises: c997cd234cd9
Create Date: 2025-10-30 09:27:39.662913

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '711f5e9f2925'
down_revision = 'c997cd234cd9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=128), nullable=False),
    sa.Column('password', sa.String(length=128), nullable=False),
    sa.Column('profile', sa.String(length=128), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user')
    # ### end Alembic commands ###
